---
# tasks file for baseline
- name: install browsers
  dnf:
    name:
      - chromium
      - qutebrowser

- name: install terminals
  dnf:
    name: alacritty

- name: install terminal applications
  dnf:
    name:
      - htop
      - lshw
      - neovim
      - ranger
      - timeshift
      - tmux
      - tlp # power management
      - zsh

- name: install programming langauages, packages, and frameworks
  dnf:
    name:
      - go
      - nodejs
      - python3-pip
      - python3-poetry

- name: install virtualization packages
  dnf:
    name: "@virtualization"

- name: install misc packages
  dnf:
    name:
      - docker
      - ImageMagick

- name: install pywal via pip
  pip:
    name: pywal

- name: install AppImageLauncher
  dnf:
    name: https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
    disable_gpg_check: true

- name: install TeamViewer
  dnf:
    name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    disable_gpg_check: true


