---
- hosts: localhost
  vars:
    task: "{{ ansible_env.HOME }}/git/ansible/vmware/tasks/esxi-data.yml"
    vmware_depot: "https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml"
    esxi_package_update: ""
    production_cluster:
      - hostname: cmch-cc-prod1.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
      - hostname: cmch-cc-prod2.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
      - hostname: cmch-cc-prod3.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
      - hostname: cmch-cc-prod4.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
    vdi_prod_cluster:
      - hostname: cmch-cc-vdi1.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
      - hostname: cmch-cc-vdi2.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
    dr_cluster:
      - hostname: cmch-cc-dr1.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
      - hostname: cmch-cc-dr2.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
    vdi_dr_cluster:
      - hostname: cmch-cc-dr3.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
      - hostname: cmch-cc-dr4.cameron.lan
        username: "cameron-admin"
        password: "ARE@ypy5efy.bfd!dpx"
  tasks:
    - name: update production_cluster
      import_tasks: "{{ task }}"
      loop: "{{ production_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"

    - name: update vdi_prod_cluster
      import_tasks: "{{ task }}"
      loop: "{{ vdi_prod_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"

    - name: update dr_cluster
      import_tasks: "{{ task }}"
      loop: "{{ dr_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"

    - name: update vdi_dr_cluster
      import_tasks: "{{ task }}"
      loop: "{{ vdi_dr_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"
