---
- hosts: localhost
  tasks:
    - name: update production_cluster
      import_tasks: "{{ task }}"
      loop: "{{ production_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"

    - name: update vdi_prod_cluster
      import_tasks: "{{ task }}"
      loop: "{{ vdi_prod_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"

    - name: update dr_cluster
      import_tasks: "{{ task }}"
      loop: "{{ dr_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"

    - name: update vdi_dr_cluster
      import_tasks: "{{ task }}"
      loop: "{{ vdi_dr_cluster }}"
      loop_control:
        loop_var: "{{ esxi }}"
