---
- name: Create share folder in share directory
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: directory
  when: item.path is defined

- name: Create Local Share Users
  ansible.windows.win_user:
    name: "{{ item.username }}"
    groups: Users
    password: "{{ item.password | default('Cameron1234!') }}"
    update_password: always

- name: Add permissions to the share folder
  ansible.windows.win_acl:
    user: "{{ item.username }}"
    path: "{{ item.path }}"
    rights: FullControl
    inherit: ContainerInherit
    type: allow
