---
- hosts: localhost 
  become: true
  tasks: 

    - name: Install baseline applications
      block:
        - name: install tools
          dnf:
            name:
              - flatpak # System Agnostic Package Management
              - filelight # Disk Usage Display
              - libreoffice # Office Suite
              - mpv # Lightweight Media Player
              - qbittorent # Torrent Client

        - name: Install Repos
          block:
            - name: Install Flatpak Repos
              community.general.flatpak_remote:
                name: flathub
                state: present
                flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
                method: user


        # - name: Install RPM Fusion Repos
        #   block:
        #     - name: Install RPM Fusion Free
        #       yum_repository:
        #         name: RPM Fusion Free
        #         description: RPM Fusion Free Repo
        #         baseurl: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-fedora.noarch.rpm

        #     - name: Install RPM Fusion Free
        #       yum_repository:
        #         name: RPM Fusion Free
        #         description: RPM Fusion Free Repo
        #         baseurl: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-fedora.noarch.rpm

        - name: install archiving tools
          dnf:
            name:
              - ark # Archive Manager
              - zip
              - unrar
              - unzip

        - name: install browsers
          dnf:
            name:
              - chromium
              - qutebrowser

        - name: install terminals and terminal software
          dnf:
            name:
              - alacritty
              - btop
              - git
              - lshw
              - tmux
              - zsh

        - name: install terminal editors
          block:
            - name: Install NeoVim
              dnf:
                name: neovim

        #     - name: Install LunarVim

        - name: install applications
          block:
            - name: install misc packages
              dnf:
                name:
                  - dunst # notifcation manager
                  - feh # wallpaper
                  - lshw
                  - tmux
                  - zsh

            - name: install backup software
              dnf:
                name:
                  - timeshift

            - name: install build software
              dnf:
                name:
                  - cmake
                  - meson

            - name: install file managers
              dnf:
                name:
                  - pcmanfm-qt
                  - ranger

            - name: install power management
              dnf:
                name:
                  - tlp
                  - xfce4-power-manager

            - name: install printing system
              dnf:
                name:
                  - cups
                  - system-config-printer

            - name: install programming langauages, packages, and frameworks
              dnf:
                name:
                  - go
                  - nodejs
                  - python3-pip
                  - python3-poetry

            - name: install virtualization packages
              dnf:
                name: "@virtualization"

            - name: install volume control
              dnf:
                name:
                  - pavucontrol

            - name: install misc packages
              dnf:
                name:
                  - docker
                  - ImageMagick

            - name: install pywal via pip
              pip:
                name: pywal

            - name: install AppImageLauncher
              dnf:
                name: https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
                disable_gpg_check: true

            - name: install TeamViewer
              dnf:
                name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
                disable_gpg_check: true
      tags: baseline

    - name: install xorg and tools
      block:
        - name: Install xorg
          dnf:
            name: "@base-x"

        - name: Install Ibhagwan fork of Picom
          block:
            - name: install dependencies
              dnf:
                name:
                  - dbus-devel
                  - gcc
                  - libconfig-devel
                  - libdrm-devel
                  - libev-devel
                  - libX11-devel
                  - libX11-xcb
                  - libXext-devel
                  - libxcb-devel
                  - libGL-devel
                  - libEGL-devel
                  - pcre-devel
                  - pcre2-devel
                  - pixman-devel
                  - uthash-devel
                  - xcb-util-image-devel
                  - xcb-util-renderutil-devel
                  - xorg-x11-proto-devel

            - name: clone repo
              git:
                repo: https://github.com/ibhagwan/picom
                depth: 1
                dest: /tmp/ibhagwan-picom
                single_branch: true
                version: next-rebase

            - name: meson setup
              shell: 
                chdir: /tmp/ibhagwan-picom
                cmd: meson setup --buildtype=release . build
                creates: /tmp/ibhagwan-picom/build/

            - name: build and install
              shell:
                chdir: /tmp/ibhagwan-picom
                cmd: ninja -C build install
                creates: /usr/local/bin/picom

        - name: Install tiling window manager packages
          block:
            - name: install xorg screen management tools
              dnf:
                name:
                  - arandr
                  - autorandr

            - name: install application launcher
              dnf:
                name:
                  - rofi
                  - rofi-themes

            - name: install logout menu
              block:
                - name: download archlinux-logout
                  git:
                    repo: https://github.com/arcolinux/archlinux-logout
                    dest: /tmp/archlinux-logout

                - name: install arcolinux-betterlockscreen
                  copy:
                    src: /tmp/archlinux-logout/usr/
                    dest: /usr/
                    mode: "755"

            - name: Install Network Manager
              dnf:
                name:
                  - NetworkManager
                  - NetworkManager-bluetooth
                  - NetworkManager-openconnect
                  - NetworkManager-tui
                  - NetworkManager-wifi
                  - network-manager-applet
                  - nm-connection-editor

            - name: Install screenlocker
              block:
                - name: install i3lock dependencies
                  dnf:
                    name:
                      - autoconf
                      - automake
                      - cairo-devel
                      - fontconfig
                      - gcc
                      - libev-devel
                      - libjpeg-turbo-devel
                      - libXinerama
                      - libxkbcommon-devel
                      - libxkbcommon-x11-devel
                      - libXrandr
                      - pam-devel
                      - pkgconf
                      - xcb-util-image-devel
                      - xcb-util-xrm-devel

                - name: download i3lock-color
                  git:
                    repo: https://github.com/Raymo111/i3lock-color.git
                    dest: /tmp/i3lock-color

                - name: install i3lock-color
                  shell:
                    chdir: /tmp/i3lock-color
                    cmd: "./install-i3lock-color.sh"
                    creates: /usr/bin/i3lock

                - name: download betterlockscreen
                  git:
                    repo: https://github.com/betterlockscreen/betterlockscreen.git
                    dest: /tmp/betterlockscreen

                - name: install betterlockscreen
                  copy: 
                    src: /tmp/betterlockscreen/betterlockscreen
                    dest: /usr/local/bin/betterlockscreen
                    mode: "755"

                - name: download arcolinux-betterlockscreen
                  git:
                    repo: https://github.com/arcolinux/arcolinux-betterlockscreen.git
                    dest: /tmp/arcolinux-betterlockscreen

                - name: install arcolinux-betterlockscreen
                  copy:
                    src: /tmp/arcolinux-betterlockscreen/usr/
                    dest: /usr/
                    mode: "755"
          tags: tiling, x11    

        - name: Install qtile dependencies
          block: 
            - name: x11 dnf
              dnf:
                name:
                  - libxkbcommon-devel
                  - picom
                  - python3-devel
                  - python3-lxml
                  - python3-psutil
                  - python3-xcffib

            - name: x11 pip
              pip:
                name:
                  - pyconfig
                  - xkbcommon

      tags: x11

    - name: install wayland and tools
      block:
        - name: install qtile dependencies
          block:
            - name: wayland dnf
              dnf:
                name:
                  - wlroots
                  # - waybar
                  - xdg-desktop-portal-wlr
                  - wdisplays
                  - wofi

            - name: wayland pip
              pip:
                name:
                  - pywayland
                  - pywlroots
      tags: wayland

    - name: Install qtile
      block:
        - name: ensure pip is installed
          dnf:
            name: python3-pip
            state: present

        - name: install common dependencies
          block:
            - name: install common dependencies (DNF)
              dnf:
                name:
                  - pango
                  - python3-cffi
                  - python3-dbus-next
                  - python3-devel

        - name: install latest qtile release
          pip:
            name: qtile
            # name: git+https://github.com/qtile/qtile.git/

        - name: create destkop entries
          block:
            - name: create wayland session
              copy:
                dest: /usr/share/wayland-sessions/qtile-wayland.desktop
                content: |
                  [Desktop Entry]
                  Name=Qtile (Wayland)
                  Comment=Qtile Session
                  Exec=qtile start -b wayland
                  Type=Application
                  Keywords=wm;tiling

            - name: create x11 session
              copy:
                dest: /usr/share/xsessions/qtile.desktop
                content: |
                  [Desktop Entry]
                  Name=Qtile
                  Comment=Qtile Session
                  Exec=qtile start
                  Type=Application
                  Keywords=wm;tiling
      tags: qtile

    - name: Setup LightDM
      block:
        - name: Install LightDM and Greeter
          dnf:
            name:
              - lightdm
              - lightdm-gtk
              - lightdm-gtk-greeter-settings

        - name: Enable LightDM Service
          systemd:
            name: lightdm.service
            state: started
            enabled: yes

        - name: Change default target to graphical.target
            file:
              src: /usr/lib/systemd/system/graphical.target
              dest: /etc/systemd/system/default.target
              state: link

    - name: configure theming
      block:
        - name: Install theme tools
          dnf:
            name:
              - kvantum
              - lxappearance
              - qt5ct

        - name: set qt5ct as qt default
          copy:
            dest: /etc/environment
            content: |
              QT_QPA_PLATFORM_THEME="qt5ct"

        - name: Install built-in themes
          dnf:
            name:
              - adwaita-cursor-theme
              - adwaita-icon-theme
              - adwaita-qt5
              - adwaita-qt6
              - breeze-cursor-theme
              - breeze-gtk-gtk3
              - breeze-icon-theme
              - plasma-breeze

        - name: Install fonts
          block:
            - name: Download Noto Font
              get_url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.1/Noto.zip
              dest: /tmp/fonts/

            - name: Install Noto Fonts
              unarchive:
                src: /tmp/fonts/Noto.zip
                dest: /usr/share/fonts

        - name: Install Wallpapers
          dnf:
            name:
              - kde-wallpapers
              - sway-wallpapers

    ## Work Programs
    - name: Install work applications
      block:
        - name: install Remmina
          community.general.flatpak:
            name: org.remmina.Remmina

        - name: install Microsoft Teams 
          community.general.flatpak:
            name: com.microsoft.Teams

        - name: install Visual Studio Code
          community.general.flatpak:
            name: com.visualstudio.code

        - name: install 1password CLI
          dnf:
            name: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
            # name: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-cli-latest.x86_64.rpm
            disable_gpg_check: true


    - name: Update Packages
      dnf:
        update_only: True
