---
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install tools
  become: true
  pacman:
    name:
      - alsa-utils
      - bc # terminal calculator
      - dnsutils
      - flatpak # System Agnostic Package Management
      - filelight # Disk Usage Display
      - jq # JSON Processor
      - less
      - libreoffice # Office Suite
      - man # Read Manual Pages
      - mpv # Lightweight Media Player
      - pacman-contrib # Tools for Pacman updates
      - qbittorrent # Torrent Client
      - tk # tkinter

- name: Setup Polkit
  block:
    - name: Install Polkit
      become: true
      pacman:
        name:
          - polkit
          - polkit-gnome

    - name: Ensure Polkit service is started
      become: true
      systemd:
        name: polkit
        state: started
        enabled: true

- name: Install Flatpak programs
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal #Flatpak Permissions GUI Manager
      - com.bitwarden.desktop
      - io.podman_desktop.PodmanDesktop
      - md.obsidian.Obsidian
      - org.remmina.Remmina

- name: Install archiving tools
  become: true
  pacman:
    name:
      - ark # Archive Manager
      - zip
      - unrar
      - unzip

- name: Install browsers
  become: true
  pacman:
    name:
      - chromium
      - qutebrowser

- name: Install browsers (AUR)
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - brave-bin

- name: Install AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - appimagelauncher
      - noisetorch
      - webapp-manager
      - ueberzugpp

- name: Install terminals and terminal software
  become: true
  pacman:
    name:
      - alacritty
      - bash-completion
      - btop
      - git
      - lshw
      - polkit-gnome
      - tmux

- name: Install NeoVim
  become: true
  pacman:
    name: neovim

- name: Install backup software
  become: true
  pacman:
    name: timeshift

- name: Install build software
  become: true
  pacman:
    name:
      - cmake
      - meson

- name: Install file managers and dependencies
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - gvfs
      - gvfs-smb
      - gvfs-mtp
      - gvfs-gphoto2
      - ranger
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-vcs-plugin
      - thunar-volman
      - tumbler # Thumbnail images for thunar
      - ueberzugpp # for image viewing in ranger

- name: Install printing system
  pacman:
    name:
      - cups
      - system-config-printer
  become: true

- name: Install programming langauages, packages, and frameworks
  become: true
  pacman:
    name:
      - go
      - gcc
      - nodejs
      - python-pip
      - python-poetry
      - python-pynvim
      - rustup

- name: Install audio and audio control
  become: true
  pacman:
    name: 
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pavucontrol
      - wireplumber

- name: Install Virtualization
  become: true
  pacman:
    name:
      - dnsmasq
      - iptables-nft
      - libvirt
      - qemu-desktop
      - swtpm
      - virt-manager

- name: Install misc packages
  become: true
  pacman:
    name:
      - docker
      - imagemagick

- name: Install xdg packages
  become: true
  pacman:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs

- name: Ensure xdg-desktop-portal-gnome is absent
  become: true
  pacman:
    name: xdg-desktop-portal-gnome
    state: absent

