---
- name: Remove AUR Builder User
  become: true
  ansible.builtin.user:
    name: aur_builder
    state: absent

- name: Remove sudo entry for `aur_builder`
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    mode: 0644
    state: absent
    validate: 'visudo -cf %s'
