---
- name: Install Hyprland 
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - hyprland

- name: Install additional Hyprland packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - hyprbars-git
      - pyprland
      - waybar
  tags: xorg

- name: Install wayland packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - azote
      - dunst
      - imv
      - gtklock
      - grim
      - light
      - nwg-look
      - nwg-displays
      - slurp
      - swaybg
      - swayidle
      - swaylock-effects
      - wlroots
      - wl-clipboard
      - wl-logout
      - wlr-randr
      - wofi

- name: Install Hyprland Contributions
  block: 
    - name: clone repo
      git:
        repo: https://github.com/hyprwm/contrib
        dest: /tmp/hyprwm-contrib

    - name: Install Grimblast
      become: true
      community.general.make:
        chdir: /tmp/hyprwm-contrib/grimblast
        target: install

