---
- name: Enable libvirt daemons
  become: true
  systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Ensure docker service is enabled
  become: true
  systemd:
    name: docker
    enabled: true

- name: Ensure podman service is enabled
  become: true
  systemd:
    name: podman
    state: started
    enabled: true

