---
- name: Install themes
  become: true
  pacman:
    name:
      - adwaita-cursors
      - adwaita-icon-theme
      - breeze
      - breeze-gtk
      - breeze-grub
      - breeze-icons
      - libadwaita
      - materia-gtk-theme

  # when: 
  #
  #- name: Install themes (Flatpak)
  #community.general.flatpak:
  #  name:
  #      -  
  #
- name: Install Flatpak themes
  community.general.flatpak:
    name:
      - org.gtk.Gtk3theme.Materia-dark-compact
  
- name: Install fonts
  become: true
  pacman:
    name:
      - ttf-noto-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common

- name: Install Wallpapers
  become: true
  pacman:
    name:
      - archlinux-wallpaper
      - plasma-workspace-wallpapers

- name: Install Qt Theme packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - qt5-styleplugins
      - qt6gtk2
      - tela-icon-theme
