---
- hosts: zabbix
  vars:
    db_user: "zabbix_db_admin"
    db_password: "TPNbg3WUGq34J@_uC76zBjhXv"
  roles:
    - role: mysql
  tasks:
    - name: Add Zabbix Repo
      yum_repository:
        name: Zabbix
        description: Zabbix RPM Repo
        baseurl: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
      become: true

    - name: Clean Repo
      shell:
        cmd: dnf clean all
      become: true

    # - name: Install MySQL
    #   import_role:
    #     name: mysql
 
    - name: Install zabbix application suite
      # ansible.builtin.dnf:
      #   - zabbix-server-mysql
      #   - zabbix-web-mysql
      #   - zabbix-apache-conf
      #   - zabbix-sql-scripts
      #   - zabbix-selinux-policy
      #   - zabbix-agent
      # become: true

    - name: Write db password to file
      ansible.builtin.lineinfile:
        path: "/etc/zabbix/zabbix_server.conf"
        search_string: 'DBPassword'
        line: "DBPassword={{ db_password }}"
        state: present
        backup: true
      become: true

    - name: Create Zabbix Database
      community.mysql.mysql_db:
        name: Zabbix
        collation: utf8mb4_bin
        encoding: utf8mb4
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        state: present

    - name: Set Zabbix db global
      community.mysql.mysql_variables:
        variable: log_bin_trust_function_creators
        value: 1
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"

    - name: Run zabbix mysql scripts
      ansible.builtin.shell:
        cmd: "zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u{{ db_user }} -p {{ db_password }}"

    - name: Set Zabbix db global
      community.mysql.mysql_variables:
        variable: log_bin_trust_function_creators
        value: 0
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"

    - name: Start Zabbix Services
      ansible.builtin.service:
        name:
          - zabbix-server
          - zabbix-agent
          - httpd
          - php-fpm
        state: restarted
        enabled: true
      become: true
