---
- hosts: localhost 
  tasks: 
    - name: Update Packages
      pacman:
        update_cache: true
        upgrade: true
      become: true

    - name: Install baseline applications
      import_tasks: baseline.yml

    - name: Configure Systemd Services
      import_tasks: services.yml

    - name: Install qtile
      import_tasks: qtile.yml
      tags: qtile

    - name: Install Hyprland
      import_tasks: hyprland.yml
      tags: hyprland

    - name: Install theming tools
      import_tasks: theme.yml

    - name: Install work Applications
      import_tasks: work.yml

    - name: Create User Folders
      shell:
        cmd: xdg-user-dirs-update
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/Documents"
