---
- hosts: localhost 
  become: true
  tasks: 
    - name: check for existing files
      block:
        - name: register status of Noto Nerd Fonts
          stat:
            path: /usr/shares/fonts/noto-nerd-fonts
          register: noto_nerd_fonts

    - name: Install baseline applications
      block:
        - name: install tools
          dnf:
            name:
              - flatpak # System Agnostic Package Management
              - qbittorrent # Torrent Client

        - name: Install Repos
          block:
            - name: Install Flatpak Repos
              community.general.flatpak_remote:
                name: flathub
                state: present
                flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
                method: system 

            - name: Install RPM Fusion Repos
              block:
              - name: Install RPM Fusion Free
                dnf:
                  name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
                  disable_gpg_check: true

              - name: Install RPM Fusion NonFree
                dnf:
                  name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
                  disable_gpg_check: true

            - name: install Flatpak programs
              community.general.flatpak:
                name:
                  - com.github.tchx84.Flatseal #Flatpak Permissions GUI Manager

        - name: install archiving tools
          dnf:
            name:
              - ark # Archive Manager
              - zip
              - unrar
              - unzip

        - name: install browsers
          dnf:
            name:
              - chromium
              - qutebrowser

        - name: install terminals and terminal software
          dnf:
            name:
              - btop
              - git
              - lshw
              - tmux
              - zsh

        - name: install terminal editors
          block:
            - name: Install NeoVim
              dnf:
                name: neovim

        - name: install applications
          block:

            - name: install backup software
              dnf:
                name:
                  - timeshift

            - name: install build software
              dnf:
                name:
                  - cmake
                  - meson

            - name: install file managers and dependencies
              dnf:
                name:
                  - ranger

            - name: install printing system
              dnf:
                name:
                  - cups
                  - system-config-printer

            - name: install programming langauages, packages, and frameworks
              dnf:
                name:
                  - cargo
                  - go
                  - gcc
                  - gcc-c++
                  - nodejs
                  - python3-pip
                  - python3-poetry
                  - rust

            - name: install powershell 7
              block:
                - name: install powershell repo
                  dnf:
                    name: https://github.com/PowerShell/PowerShell/releases/download/v7.3.2/powershell-7.3.2-1.rh.x86_64.rpm
                    disable_gpg_check: true

                - name: install powershell
                  dnf:
                    name: powershell

            - name: install virtualization packages
              dnf:
                name: "@virtualization"

            - name: install AppImageLauncher
              dnf:
                name: https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
                disable_gpg_check: true

            - name: install TeamViewer
              dnf:
                name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
                disable_gpg_check: true
                
      tags: baseline

    - name: Install Gnome Basics
      dnf:
        name:
          - gnome-extensions-app
          - gnome-tweaks

    - name: Install Gnome Extensions
      dnf:
        name:
          - gnome-shell-extension-appindicator
          - gnome-shell-extension-auto-move-windows
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-gsconnect
          - gnome-shell-extension-launch-new-instance

    - name: Install built-in themes
      dnf:
        name:
          - adwaita-cursor-theme
          - adwaita-icon-theme
          - adwaita-qt5
          - adwaita-qt6
          - breeze-cursor-theme
          - breeze-gtk-gtk3
          - breeze-icon-theme
          - plasma-breeze

    - name: Install fonts
      when: not noto_nerd_fonts.stat.exists
      block:
        - name: create fonts temp folder
          file:
            path: /usr/share/fonts/noto-nerd-fonts
            state: directory

        - name: Download Noto Font
          get_url:
            url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.1/Noto.zip
            dest: /tmp/

        - name: Install Noto Fonts
          unarchive:
            src: /tmp/Noto.zip
            dest: /usr/share/fonts/noto-nerd-fonts

    - name: Install Wallpapers
      dnf:
        name:
          - kde-wallpapers
          - sway-wallpapers

    ## Work Programs
    - name: Install work applications
      block:
        - name: install Remmina
          community.general.flatpak:
            name: org.remmina.Remmina

        - name: install Microsoft Teams 
          community.general.flatpak:
            name: com.microsoft.Teams

        - name: install Visual Studio Code
          community.general.flatpak:
            name: com.visualstudio.code

        # - name: install 1password
        #   block:
        #     - name: add 1Password repo
        #       yum_repository:
        #         name: 1password
        #         description: 1Password RPM Repository
        #         baseurl: https://downloads.1password.com/linux/rpm/stable/\$basearch
        #         gpgkey: https://downloads.1password.com/linux/keys/1password.asc
        #
        #     - name: install 1Password apps
        #       dnf:
        #         name:
        #           - 1password
        #           - 1password-cli


    - name: Update Packages
      dnf:
        update_only: True
