---
- hosts: localhost 
  pre_tasks:
    - name: check for existing files
      block:
        - name: register status of Noto Nerd Fonts
          stat:
            path: /usr/shares/fonts/noto-nerd-fonts
          register: noto_nerd_fonts

        - name: register status of betterlockscreen
          stat:
            path: /usr/local/bin/arcolinux-betterlockscreen
          register: betterlockscreen

        - name: register status of Nordic theme
          stat:
            path: /usr/share/themes/Nordic
          register: nordic_theme

        - name: register status of Nordzy-cyan-dark icons
          stat:
            path: /usr/share/icons/Nordzy-cyan-dark
          register: nordzy_icons

        - name: register status of lockscreen
          stat:
            path: /usr/local/bin/i3lock
          register: lockscreen

        - name: register status of logout
          stat:
            path: /usr//bin/archlinux-logout
          register: logout

  tasks: 
    - name: Update Packages
      dnf:
        update_only: True
      become: True

    - name: Install baseline applications
      import_tasks: baseline.yml

    - name: Install window manager related applications
      import_tasks: window_manager.yml

    - name: Install qtile
      import_tasks: qtile.yml
      tags: qtile

    - name: Install theming tools
      import_tasks: theme.yml

    - name: Install work Applications
      import_tasks: work.yml

    - name: Create User Folders
      shell:
        cmd: xdg-user-dirs-update
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/Documents"

