---
- hosts: localhost 
  # become: true
  tasks: 
    - name: check for existing files
      block:
        - name: register status of Noto Nerd Fonts
          stat:
            path: /usr/shares/fonts/noto-nerd-fonts
          register: noto_nerd_fonts

        - name: register status of betterlockscreen
          stat:
            path: /usr/local/bin/arcolinux-betterlockscreen
          register: betterlockscreen

    - name: install baseline applications
      import_tasks: window_manager.yml
    # - name: Setup LightDM
    #   block:
    #     - name: Install LightDM and Greeter
    #       dnf:
    #         name:
    #           - lightdm
    #           - lightdm-gtk
    #           - lightdm-gtk-greeter-settings
    #
    #     - name: Enable LightDM Service
    #       systemd:
    #         name: lightdm.service
    #         state: started
    #         enabled: yes
    #
    #     - name: Change default target to graphical.target
    #       file:
    #         src: /usr/lib/systemd/system/graphical.target
    #         dest: /etc/systemd/system/default.target
    #         state: link

    - name: install window manager related applications
      import_tasks: window_manager.yml

    - name: install qtile
      import_tasks: qtile.yml

    - name: install theming tools
      import_tasks: theme.yml

    - name: install work Applications
      import_tasks: work.yml

    - name: Update Packages
      dnf:
        update_only: True

    - name: Create User Folders
      shell:
        cmd: xdg-user-dirs-update
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/Documents"

