---
# tasks file for work
- name: install Remmina
  dnf:
    name: remmina

- name: install Microsoft Teams
  dnf:
    name: https://packages.microsoft.com/yumrepos/ms-teams/teams-1.5.00.10453-1.x86_64.rpm
    disable_gpg_check: true

- name: install 1password CLI
  dnf:
    name: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-cli-latest.x86_64.rpm
    disable_gpg_check: true

