---
- hosts: FTP
  vars:
    shares:
      - name: parkview
    domain: cameron.lan
  pre_tasks:
  tasks:
    - name: Create entry for domain membership
      lineinfile:
        path: /etc/samba/smb.conf
        search_string: security
        line: security = ads

    - name: Create Windows Domain entry in samba config 
      lineinfile:
        path: /etc/samba/samba.conf
        search_string: workgroup
        line: workgroup = {{ domain }}
      when: domain is defined


    - name: Create share entries in samba config
      blockinfile:
        path: /etc/samba/samba.conf
        block: |
          [{{ item.name }}]
          comment = {{ item.comment }}
          path = {{ item.path }}
          public = {{ item.public | default(no) }}
          writable = {{ item.writable | default(no) }}
          printable = {{ item.printable | default(no) }}
    
