---
- name: Configure AD Domain Controllers
  hosts: dcs
  remote_user: administrator

  tasks:
    - name: Make server domain controller
      block:
        - name: Add server to domain controller
          win_domain_membership:

          register: domain_join

        - name: Reboot to complete domain join when needed
          win_reboot:
          when: domain_join.reboot_required

        - name: Promote server to domain controller
          win_domain_controller:
            dns_domain_name: cameron.lan
            domain_admin_user: administrator
            domain_admin_password: "{{ domain_admin_password }}"
            state: domain_controller
          register: dc_promote
    
        - name: Reboot to complete dc promotion when needed
          win_reboot:
          when: dc_promote.reboot_required
      

# vim:ft=yaml.ansible
