---
- name: Configure AD Domain Controllers
  hosts: dcs
  remote_user: administrator

  tasks:
    - name: Update server
      ansible.windows.win_updates:
        reboot: false

    - name: Make server domain controller
      block:
        - name: Promote server to domain controller
          win_domain_controller:
            dns_domain_name: cameron.lan
            domain_admin_user: administrator
            domain_admin_password: "{{ domain_admin_password }}"
            state: domain_controller
          register: dc_promote
    
        - name: Reboot to complete dc promotion when needed
          win_reboot:
          when: dc_promote.reboot_required
      
    - name: Configure DHCP

    - name: Configure DNS

    - name: Configure Scheduled Tasks

# vim:ft=yaml.ansible
